version: '3.9'
services:
    backend:
      build: .
      ports:
        - 8000:3000
      volumes:
        - .:/app
      depends_on:
        - db
     
    db:
      image: postgres
      restart: always
      env_file:
        - database.env
      volumes:
        - .database-data:/var/lib/postgresql/data/
      ports:
        - 5433:5432 
